#!/usr/bin/env python

# Munin plugin for graphing amount of dcs-get installations
#
# 1. Link/copy this to /etc/munin/plugins
# 2. Add the following to /etc/munin/plugin-conf.d/munin-node
#
#       [dcs_get_requests]
#       user root


import re
import sys

# Get all file-version data from packages.json

if len(sys.argv) == 2 and sys.argv[1] == "config":
	print "graph_title dcs-get Installations"
	print "graph_args --base 1000"
	print "graph_vlabel installs"
	print "graph_category dcs-get"
	print "installs.label installs"
	print "installs.type DERIVE"
	print "installs.min 0"
	exit(0)

# Count how many requests to dcs-get-install there are

install_count = 0


# We assume use of apache as a webserver.
# Substitute the file below for an equivalent

with open("/var/log/apache2/access.log") as log:
  	for log_line in log.readlines():
		m = re.match(r".*/dcs-get-install.*", log_line)
		if not m == None:
				install_count += 1

print "installs.value %d" % install_count
