#!/usr/bin/env python

# Munin plugin for graphing amount of package downloads.
#
# 1. Link/copy this to /etc/munin/plugins
# 2. Add the following to /etc/munin/plugin-conf.d/munin-node
#
# 	[dcs_get_package_downloads]
# 	user root

import re
import sys

if len(sys.argv) == 2 and sys.argv[1] == "config":
	print "graph_title dcs-get Package Downloads"
	print "graph_args --base 1000"
	print "graph_vlabel Downloads"
	print "graph_category dcs-get"
	print "downloads.label Package Downloads"
	print "downloads.type DERIVE"
	print "downloads.min 0"
	exit(0)

installation_count = 0

# Count how many package downloads there are.
# We assume use of apache2 as a webserver, substitute the file below otherwise

with open("/var/log/apache2/access.log") as log:
  	for log_line in log.readlines():
		m = re.match(r".*/packages/(.*)-.*.tar.gz", log_line)
		if not m == None:
			installation_count += 1

print "downloads.value %d" % installation_count
